/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    ChatHeader: typeof import('./src/components/chat/ChatHeader.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/chat/ChatMessage.vue')['default']
    ChatView: typeof import('./src/components/chat/ChatView.vue')['default']
    ConversationItem: typeof import('./src/components/layout/ConversationItem.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    MarkdownRenderer: typeof import('./src/components/chat/MarkdownRenderer.vue')['default']
    MessageList: typeof import('./src/components/chat/MessageList.vue')['default']
    PaperManagerModal: typeof import('./src/components/modals/PaperManagerModal.vue')['default']
    PaperSelectModal: typeof import('./src/components/modals/PaperSelectModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanModal: typeof import('./src/components/modals/ScanModal.vue')['default']
    SearchModeToggle: typeof import('./src/components/chat/SearchModeToggle.vue')['default']
    SidebarFooter: typeof import('./src/components/layout/SidebarFooter.vue')['default']
    UploadModal: typeof import('./src/components/modals/UploadModal.vue')['default']
  }
}
